;;; rg-bibtex-test.el --- Tests for local BibTeX helpers -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'rg-bibtex)

(defvar bibtex-completion-bibliography)
(defvar citar-bibliography)
(defvar org-cite-basic-mouse-over-key-face)
(defvar org-cite-global-bibliography)

(ert-deftest rg-bibtex-cache-path-defaults-to-xdg-cache ()
  (let ((process-environment '("XDG_CACHE_HOME=/tmp/rg-cache")))
    (should
     (equal (rg/bibtex-default-cache-file)
            "/tmp/rg-cache/doom/zotLib.bib"))))

(ert-deftest rg-bibtex-clean-cache-path-defaults-to-xdg-cache ()
  (let ((process-environment '("XDG_CACHE_HOME=/tmp/rg-cache")))
    (should
     (equal (rg/bibtex-default-clean-cache-file)
            "/tmp/rg-cache/doom/zotLib.clean.bib"))))

(ert-deftest rg-bibtex-cache-selection-prefers-readable-cache ()
  (let ((source "/tmp/rg-bibtex-source.bib")
        (cache "/tmp/rg-bibtex-cache.bib"))
    (with-temp-file source (insert "@article{source}\n"))
    (with-temp-file cache (insert "@article{cache}\n"))
    (let ((zot_bib_source source)
          (zot_bib_cache cache))
      (should (equal (rg/zot-bib-use-cache) cache)))))

(ert-deftest rg-bibtex-cache-selection-prefers-readable-clean-cache ()
  (let ((source "/tmp/rg-bibtex-source.bib")
        (cache "/tmp/rg-bibtex-cache.bib")
        (clean-cache "/tmp/rg-bibtex-clean-cache.bib"))
    (with-temp-file source (insert "@article{source}\n"))
    (with-temp-file cache (insert "@article{cache}\n"))
    (with-temp-file clean-cache (insert "@article{clean}\n"))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache))
      (should (equal (rg/zot-bib-use-cache) clean-cache)))))

(ert-deftest rg-bibtex-cache-selection-updates-citation-consumers ()
  (let ((source "/tmp/rg-bibtex-source-consumers.bib")
        (cache "/tmp/rg-bibtex-cache-consumers.bib")
        (clean-cache "/tmp/rg-bibtex-clean-cache-consumers.bib")
        (org-cite-global-bibliography 'old-org-cite)
        (citar-bibliography 'old-citar)
        (bibtex-completion-bibliography 'old-bibtex-completion))
    (with-temp-file source (insert "@article{source}\n"))
    (with-temp-file cache (insert "@article{cache}\n"))
    (with-temp-file clean-cache (insert "@article{clean}\n"))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache))
      (should (equal (rg/zot-bib-use-cache) clean-cache))
      (should (equal org-cite-global-bibliography (list clean-cache)))
      (should (equal citar-bibliography (list clean-cache)))
      (should (equal bibtex-completion-bibliography (list clean-cache))))))

(ert-deftest rg-bibtex-citar-fast-activate-avoids-cache-lookup ()
  (with-temp-buffer
    (insert "cite:@sample")
    (let ((org-cite-basic-mouse-over-key-face 'highlight)
          (cache-called nil))
      (cl-letf (((symbol-function 'org-cite-boundaries)
                 (lambda (_citation)
                   (cons (point-min) (point-max))))
                ((symbol-function 'org-cite-get-references)
                 (lambda (_citation)
                   '(reference)))
                ((symbol-function 'org-cite-key-boundaries)
                 (lambda (_reference)
                   (cons 7 13)))
                ((symbol-function 'citar-get-entries)
                 (lambda ()
                   (setq cache-called t)
                   (make-hash-table :test 'equal))))
        (rg/citar-org-fast-activate 'citation)
        (should-not cache-called)
        (should (eq (get-text-property (point-min) 'font-lock-multiline) t))
        (should (get-text-property (point-min) 'face))
        (should (get-text-property 7 'mouse-face))
        (should (get-text-property 7 'face))))))

(ert-deftest rg-bibtex-cache-selection-falls-back-to-source ()
  (let ((source "/tmp/rg-bibtex-source.bib")
        (cache "/tmp/rg-bibtex-missing.bib"))
    (with-temp-file source (insert "@article{source}\n"))
    (let ((zot_bib_source source)
          (zot_bib_cache cache))
      (should (equal (rg/zot-bib-use-cache) source)))))

(ert-deftest rg-bibtex-configure-paths-uses-environment ()
  (let ((process-environment
         '("RG_ORG_NOTES_DIR=/tmp/rg-notes"
           "RG_ZOT_BIB=/tmp/rg-zot.bib"
           "RG_ZOT_BIB_CACHE=/tmp/rg-zot-cache.bib"
           "RG_ZOT_BIB_CLEAN_CACHE=/tmp/rg-zot-clean-cache.bib")))
    (makunbound 'org_notes)
    (makunbound 'zot_bib_source)
    (makunbound 'zot_bib_cache)
    (makunbound 'zot_bib_clean_cache)
    (rg/bibtex-configure-paths)
    (should (equal org_notes "/tmp/rg-notes/"))
    (should (equal zot_bib_source "/tmp/rg-zot.bib"))
    (should (equal zot_bib_cache "/tmp/rg-zot-cache.bib"))
    (should (equal zot_bib_clean_cache "/tmp/rg-zot-clean-cache.bib"))))

(ert-deftest rg-bibtex-sanitize-removes-escaped-braces ()
  (with-temp-buffer
    (insert "@unpublished{sample,\n")
    (insert "  author = {Mahmoud\\}, Chiheb \\{Ben and Cs\\'anyi, G\\'abor}\n")
    (insert "}\n")
    (rg/bibtex-sanitize-buffer)
    (should
     (string-match-p
      "author = {Mahmoud, Chiheb Ben and Cs\\\\'anyi, G\\\\'abor}"
      (buffer-string)))))

(ert-deftest rg-bibtex-refresh-cache-writes-clean-cache ()
  (let ((source "/tmp/rg-bibtex-source-refresh.bib")
        (cache "/tmp/rg-bibtex-cache-refresh.bib")
        (clean-cache "/tmp/rg-bibtex-clean-cache-refresh.bib"))
    (with-temp-file source
      (insert "@unpublished{sample,\n")
      (insert "  author = {Mahmoud\\}, Chiheb \\{Ben and Anelli, Andrea}\n")
      (insert "}\n"))
    (ignore-errors (delete-file cache))
    (ignore-errors (delete-file clean-cache))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache))
      (should (equal (rg/zot-bib-refresh-cache) clean-cache))
      (should (file-readable-p cache))
      (should (file-readable-p clean-cache))
      (with-temp-buffer
        (insert-file-contents clean-cache)
        (should
         (string-match-p
          "author = {Mahmoud, Chiheb Ben and Anelli, Andrea}"
          (buffer-string)))))))

(ert-deftest rg-bibtex-cache-stale-when-clean-cache-missing ()
  (let ((source "/tmp/rg-bibtex-source-stale.bib")
        (cache "/tmp/rg-bibtex-cache-stale.bib")
        (clean-cache "/tmp/rg-bibtex-clean-cache-missing.bib"))
    (with-temp-file source (insert "@article{source}\n"))
    (ignore-errors (delete-file clean-cache))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache))
      (should (rg/zot-bib-cache-stale-p)))))

(ert-deftest rg-bibtex-cache-stale-when-source-is-newer ()
  (let ((source "/tmp/rg-bibtex-source-newer.bib")
        (cache "/tmp/rg-bibtex-cache-newer.bib")
        (clean-cache "/tmp/rg-bibtex-clean-cache-older.bib"))
    (with-temp-file source (insert "@article{source}\n"))
    (with-temp-file clean-cache (insert "@article{clean}\n"))
    (set-file-times clean-cache (encode-time 0 0 0 1 1 2024))
    (set-file-times source (encode-time 0 0 0 1 1 2025))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache))
      (should (rg/zot-bib-cache-stale-p)))))

(ert-deftest rg-bibtex-cache-current-when-clean-cache-is-newer ()
  (let ((source "/tmp/rg-bibtex-source-older.bib")
        (cache "/tmp/rg-bibtex-cache-older.bib")
        (clean-cache "/tmp/rg-bibtex-clean-cache-newer.bib"))
    (with-temp-file source (insert "@article{source}\n"))
    (with-temp-file clean-cache (insert "@article{clean}\n"))
    (set-file-times source (encode-time 0 0 0 1 1 2024))
    (set-file-times clean-cache (encode-time 0 0 0 1 1 2025))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache))
      (should-not (rg/zot-bib-cache-stale-p)))))

(ert-deftest rg-bibtex-async-refresh-skips-current-cache ()
  (let ((source "/tmp/rg-bibtex-async-source-current.bib")
        (cache "/tmp/rg-bibtex-async-cache-current.bib")
        (clean-cache "/tmp/rg-bibtex-async-clean-current.bib")
        (started nil))
    (with-temp-file source (insert "@article{source}\n"))
    (with-temp-file clean-cache (insert "@article{clean}\n"))
    (set-file-times source (encode-time 0 0 0 1 1 2024))
    (set-file-times clean-cache (encode-time 0 0 0 1 1 2025))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache)
          (rg/zot-bib-refresh-cache-async-running nil))
      (cl-letf (((symbol-function 'rg/bibtex--async-start)
                 (lambda (&rest _)
                   (setq started t))))
        (should-not (rg/zot-bib-refresh-cache-async))
        (should-not started)))))

(ert-deftest rg-bibtex-async-refresh-starts-for-stale-cache ()
  (let ((source "/tmp/rg-bibtex-async-source-stale.bib")
        (cache "/tmp/rg-bibtex-async-cache-stale.bib")
        (clean-cache "/tmp/rg-bibtex-async-clean-stale.bib")
        (started nil))
    (with-temp-file source (insert "@article{source}\n"))
    (ignore-errors (delete-file clean-cache))
    (let ((zot_bib_source source)
          (zot_bib_cache cache)
          (zot_bib_clean_cache clean-cache)
          (rg/zot-bib-refresh-cache-async-running nil))
      (cl-letf (((symbol-function 'rg/bibtex--async-start)
                 (lambda (_start _finish)
                   (setq started t)
                   'fake-process)))
        (should (eq (rg/zot-bib-refresh-cache-async) 'fake-process))
        (should started)
        (should (eq rg/zot-bib-refresh-cache-async-running 'fake-process))))))

(ert-deftest rg-bibtex-async-refresh-finish-clears-running-state ()
  (let ((zot_bib_clean_cache "/tmp/rg-bibtex-async-clean-finished.bib")
        (rg/zot-bib-refresh-cache-async-running 'fake-process))
    (with-temp-file zot_bib_clean_cache (insert "@article{clean}\n"))
    (rg/zot-bib-refresh-cache-async-finish
     (list :ok t :path zot_bib_clean_cache))
    (should-not rg/zot-bib-refresh-cache-async-running)
    (should (equal zot_bib zot_bib_clean_cache))))

(ert-deftest rg-bibtex-auto-refresh-uses-idle-timer ()
  (let ((rg/zot-bib-auto-refresh-timer nil)
        (rg/zot-bib-auto-refresh-idle-delay 7)
        captured)
    (cl-letf (((symbol-function 'run-with-idle-timer)
               (lambda (seconds repeat function &rest args)
                 (setq captured (list seconds repeat function args))
                 'fake-timer)))
      (should (eq (rg/zot-bib-enable-auto-refresh) 'fake-timer))
      (should (equal captured
                     '(7 t rg/zot-bib-refresh-cache-on-idle nil))))))

(provide 'rg-bibtex-test)
;;; rg-bibtex-test.el ends here
