#+TITLE: Emacs Literate Package Additions
#+AUTHOR: Rohit Goswami (HaoZeke) <rohit.goswami@aol.com>
#+DATE: 2020:04:09
#+HTML_LINK_HOME: https://dotdoom.rgoswami.me
#+HTML_HEAD_EXTRA: <script> window.goatcounter = { path: '/dotdoomhome', }; </script>
#+HTML_HEAD_EXTRA: <script data-goatcounter="https://rgoswami.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
#+PROPERTY: header-args :tangle (concat doom-private-dir "packages.el")
#+PROPERTY: header-args+ :comments link
#+STARTUP: outline
#+OPTIONS: toc:nil

# Now we set this with STARTUP
# These can be set per subtree.
# :PROPERTIES:
# :VISIBILITY: children
# :END:

** Table of Contents :TOC_3_gh:noexport:
  - [[#about-this-file][About this file]]
    - [[#about-that-toc][About that TOC..]]
    - [[#the-properties][The properties]]
  - [[#aesthetic-packages][Aesthetic Packages]]
    - [[#dired-icons][Dired Icons]]
    - [[#wakatime][Wakatime]]
    - [[#bufler][Bufler]]
  - [[#later-magit-additions][LATER Magit Additions]]
  - [[#key-chords-and-keybindings][Key Chords and Keybindings]]
  - [[#evil-colemak][Evil Colemak]]
  - [[#firestarter][Firestarter]]
  - [[#org-additions][Org Additions]]
    - [[#org-download][Org Download]]
    - [[#later-org-drill][LATER Org Drill]]
    - [[#org-protocol-updates][Org Protocol Updates]]
    - [[#org-noter][Org Noter]]
    - [[#org-ref][Org Ref]]
    - [[#org-mind-map][Org Mind Map]]
    - [[#org-rifle][Org Rifle]]
    - [[#org-async][Org Async]]
    - [[#anki-mode][Anki Mode]]
    - [[#org-re-reveal-extensions][Org Re-Reveal Extensions]]
    - [[#org-roam-bibtex][Org Roam Bibtex]]
    - [[#org-gcal][Org GCal]]
  - [[#dockerfile-mode][Dockerfile Mode]]
  - [[#reference-management][Reference Management]]
  - [[#syntax-highlighting][Syntax Highlighting]]
    - [[#sphinx-and-rst][Sphinx and RsT]]
    - [[#cpp-additions][CPP Additions]]
    - [[#tup-mode][Tup Mode]]
    - [[#saltstack-mode][SaltStack Mode]]
    - [[#pkgbuild-mode][PKGBUILD Mode]]
    - [[#lammps-mode][LAMMPS Mode]]
    - [[#pug-mode][Pug Mode]]
    - [[#nix-mode][Nix Mode]]
    - [[#jvm-languages][JVM Languages]]
    - [[#systemd-mode][Systemd Mode]]
    - [[#dart-mode][Dart Mode]]
    - [[#wolfram-mode][Wolfram Mode]]
    - [[#polymode][Polymode]]
  - [[#flycheck-additions][Flycheck Additions]]
    - [[#melpa-helper][MELPA Helper]]
  - [[#snippets][Snippets]]
    - [[#doom][Doom]]
    - [[#standard][Standard]]
  - [[#math-support][Math support]]

** About this file
This is an Emacs literate package file and is meant to compliment [[file:config.org][my
configuration]], as well as [[file:index.html][the init.el]]. It contains the basic structure along
with some data about each package and why it's needed. This is to be used in
tandem with the ~define-package!~ function in ~config.org~.

Since it's primarily aimed at ~doom-emacs~ let's add their comments.

#+BEGIN_SRC emacs-lisp
;; -*- no-byte-compile: t; -*-
;;; ~/.config/doom/packages.el
#+END_SRC

*** About that TOC..
So as mentioned [[https://github.com/snosov1/toc-org/issues/35][here]] there is trouble when ~org-export~ tries to create files
while keeping the ~org-toc~ tag.

It's not really a problem since ~org-export~ actually generates a TOC for the
files anyway.
*** The properties
Basically, the properties set imply that the file is to be tangled for every
block and moreover the output directory is the ~doom-private-dir~. It's
practically self explanatory but still. 

The filename is determined by the ~SRC~ block languages.
** Aesthetic Packages
*** Dired Icons
Since treemacs already uses ~all-the-icons~ it is silly to not use them in
dired, from the [[https://github.com/domtronn/all-the-icons.el/wiki][all-the-icons wiki]].
#+BEGIN_SRC emacs-lisp
(package! all-the-icons-dired)
#+END_SRC
*** Wakatime
Not exactly aesthetic, but yeah, for stats.
#+BEGIN_SRC emacs-lisp :tangle yes
(package! wakatime-mode)
#+END_SRC
*** Bufler
[[https://github.com/alphapapa/bufler.el][This package]] seems to have better control of buffers than the default mess.
#+begin_src elisp
(package! bufler)
#+end_src
** LATER Magit Additions
These basically allow for TODOs in magit along with enhanced github integration.
These have been added upstream in ~develop~.

#+BEGIN_SRC emacs-lisp :tangle no
(package! magit-org-todos)
(package! magithub)
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
(package! magit-todos)
#+END_SRC

Actually [[https://github.com/alphapapa/magit-todos][magit-todos]] has been added upstream which collates all ~todo~ items.
There might still be workflows where [[https://github.com/danielma/magit-org-todos.el][magit-org-todos]] is useful since that
displays a global ~todo.org~ file.
** DONE Key Chords and Keybindings
It turns out that the switch to [[https://github.com/noctuid/general.el][general.el]] is both inevitable (doom version 2.1)
and very rational. However, I really can't wait. So.. This is a stop gap solution.
#+BEGIN_SRC emacs-lisp :tangle no
(package! general)
#+END_SRC
- [x] Remove when it's merged upstream
** Evil Colemak
I guess I just gave up, [[https://github.com/wbolster/evil-colemak-basics][from here]]. Read about why [[https://rgoswami.me/posts/colemak-dots-refactor/][here]]. The visual line mode setup leverages [[https://github.com/YourFin/evil-better-visual-line/][this package]].
#+begin_src emacs-lisp :tangle yes
(package! evil-colemak-basics)
(package! evil-better-visual-line)
#+end_src

** Firestarter
For running shell commands on-save.

#+BEGIN_SRC emacs-lisp :tangle yes
(package! firestarter)
#+END_SRC

** Org Additions
The new ones need to be covered in the ~config.org~ file with the appropriate
keybindings. The notes are [[https://rgoswami.me/posts/org-note-workflow][described here]].
*** Org Download
Now I load it here since I don't use ~+attach~.
#+BEGIN_SRC emacs-lisp
(package! org-download
  :recipe (:host github
            :repo "abo-abo/org-download"))
#+END_SRC

*** LATER Org Drill
The [[https://bitbucket.org/eeeickythump/org-drill/src][actual repo]] has not been updated in 3 years, so I must use [[https://github.com/hakanserce/org-drill][this fork]].
#+BEGIN_SRC emacs-lisp :tangle yes
(package! org-drill
  :recipe (:host github
            :repo "hakanserce/org-drill"))
#+END_SRC

*** Org Protocol Updates
This needs to be installed specially, [[https://github.com/alphapapa/org-protocol-capture-html][from this repo]].
#+BEGIN_SRC emacs-lisp
(package! org-protocol-capture-html
  :recipe (:host github
           :repo "alphapapa/org-protocol-capture-html"))
#+END_SRC
*** TODO Org Noter
This is sort of more of a ~pdf-tools~ extension and it needs it's own ~biblatex~
setup and stuff as well so this might move into a tree of it's own.

#+BEGIN_SRC emacs-lisp
(package! org-noter)
#+END_SRC

This actually breaks the ~pdf-tools~ bindings.

*** Org Ref
This is probably not the best thing in my current setup.. Now part of the ~init.el~ setup.

#+BEGIN_SRC emacs-lisp
(package! org-ref)
#+END_SRC
*** Org Mind Map
Not on MELPA yet. From [[https://github.com/theodorewiles/org-mind-map][here]].
#+BEGIN_SRC emacs-lisp
(package! org-mind-map
  :recipe (:host github
            :repo "theodorewiles/org-mind-map"))
#+END_SRC
*** Org Rifle
Technically a helm addition. Perfect for monolithic ~org~ files. More details
[[https://github.com/alphapapa/helm-org-rifle][here]].
#+BEGIN_SRC emacs-lisp
(package! helm-org-rifle)
#+END_SRC
*** Org Async
We will use this.
#+begin_src emacs-lisp :tangle yes
(package! org-babel-eval-in-repl)
#+end_src
*** Anki Mode
This is put here since it only works with ~org-mode~ stuff.
#+BEGIN_SRC emacs-lisp
(package! anki-editor)
#+END_SRC

*** Org Re-Reveal Extensions
An [[https://gitlab.com/oer/org-re-reveal-ref][extension]] to ~org-re-reveal-ref~. Also [[https://gitlab.com/oer/oer-reveal][this]].
#+begin_src emacs-lisp :tangle yes
(package! org-re-reveal-ref)
#+end_src
*** Org Roam Bibtex
This should be a part of the main ~+roam~ setup, but until then.
#+begin_src emacs-lisp :tangle yes
(package! org-roam-bibtex)
#+end_src
*** Org GCal
This extension seems to be a maintained fork.
#+begin_src emacs-lisp :tangle yes
(package! org-gcal)
#+end_src
** Dockerfile Mode
For syntax highlighting and inline builds. [[https://github.com/spotify/dockerfile-mode][From spotify]] weirdly.
~## -*- docker-image-name: "your-image-name-here" -*-~ can be used to specify
the image name.
#+BEGIN_SRC emacs-lisp
(package! dockerfile-mode)
#+END_SRC
** Reference Management
**** Zotero
There are a bunch of ~zotero~ integrations for emacs, most notably, [[https://github.com/vspinu/zotelo][zotelo]], but
they don't seem to be all that well mantained. [[https://github.com/emacsmirror/zotxt][Zotxt]] seems to be updated pretty
often though.

#+BEGIN_SRC emacs-lisp
(package! zotxt)
#+END_SRC
** Syntax Highlighting
These are additionally required to work with the sort of files I use often.
The configuration and settings are as usual in ~config.org~
*** Sphinx and RsT
Though reStructured Text is supported natively, there are some quality of life exporters and packages which should be more useful.
#+begin_src emacs-lisp
(package! ox-rst
  :recipe (:host github
           :repo "msnoigrs/ox-rst"))
(package! sphinx-mode
  :recipe (:host github
           :repo "Fuco1/sphinx-mode"
           :files ("*.el")))
#+end_src
*** CPP Additions
Though the standard ~doom-emacs~ module configuration is a sane set of defaults, there are some glaring omissions, most egregious of is the lack of ~doxygen~ highlighting.
#+begin_src emacs-lisp
(package! highlight-doxygen)
#+end_src
*** Tup Mode
Because honestly there isn't anything better than [[http://gittup.org/tup/][tup]]. Who doesn't need a build
system which [[http://gittup.org/tup/tup_vs_mordor.html][scales with the eye of Mordor]]?

#+BEGIN_SRC emacs-lisp
(package! tup-mode
:recipe (:host github
           :repo "ejmr/tup-mode"))
#+END_SRC

**** LATER Caveats
The repo is unmaintained so I ought to fork it and take a look into maintaining it.
*** SaltStack Mode
I have recently decided that [[https://saltstack.com/][saltstack]] ought to be used for working on multiple
systems.

#+BEGIN_SRC emacs-lisp
(package! salt-mode
:recipe (:host github
         :repo "glynnforrest/salt-mode"))
#+END_SRC
*** PKGBUILD Mode
No point using ~emacs~ if I can't get highlighting for all my needs. This needs
some extra configuration. +Must figure out if this is well mantained+. The
developer is very responsive to pull requests and the like.

#+BEGIN_SRC emacs-lisp
(package! pkgbuild-mode
  :recipe (:host github
            :repo "juergenhoetzel/pkgbuild-mode"))
#+END_SRC
*** LAMMPS Mode
+This could do with some updates. Will look into this soon. Also it takesunbearably long this way. Must figure out how to stop it from downloading the
whole repo.+
Mantained [[https://github.com/HaoZeke/lammps-mode][by me]] now.
#+BEGIN_SRC emacs-lisp
(package! lammps-mode
  :recipe (:host github
                    :repo "HaoZeke/lammps-mode"))
#+END_SRC
*** Pug Mode
I just like pugs.
#+BEGIN_SRC emacs-lisp
(package! pug-mode)
#+END_SRC
*** Nix Mode
For building more cross-os stuff. This is the [[https://github.com/NixOS/nix-mode][official package]], but will look
into binding and using [[https://github.com/travisbhartwell/nix-emacs][nix-emacs]] as well.
#+BEGIN_SRC emacs-lisp
(package! nix-mode)
#+END_SRC
*** JVM Languages
Currently the languages I care about (apart from Java) are:
#+BEGIN_SRC emacs-lisp
; Kotlin > Java
(package! kotlin-mode)
; Groovy -> Testing
(package! groovy-mode)
#+END_SRC
*** Systemd Mode
Since I use a lot of user systemd units, it makes sense to have pretty
highlighting.
#+BEGIN_SRC emacs-lisp
(package! systemd)
#+END_SRC
*** Dart Mode
Might eventually want to also get the companion [[https://github.com/bradyt/dart-server][dart server]] sometime, but for
now this syntax-highlighter will do. Might actually want to see if ~prettier~
has anything for it.
#+BEGIN_SRC emacs-lisp :tangle no
(package! dart-mode)
#+END_SRC
*** Wolfram Mode
Actually ~wolfram-mode~ seems to be able to do more than just syntax highlighting, but at the moment I just need font-locking.
#+BEGIN_SRC emacs-lisp
(package! wolfram-mode)
#+END_SRC
*** Polymode
For working with ~.Rmd~ files and better ~orgmode~ R support.
#+BEGIN_SRC emacs-lisp
(package! poly-R)
(package! poly-org)
#+END_SRC
** Flycheck Additions
*** MELPA Helper
This is for linting files before submitting to MELPA.
#+BEGIN_SRC emacs-lisp
(package! package-lint)
(package! flycheck-package)
#+END_SRC
** Snippets
These are from [[https://github.com/hlissner][hlissner]].
*** Doom
#+BEGIN_SRC emacs-lisp
(package! emacs-snippets
  :recipe (:host github
           :repo "hlissner/emacs-snippets"
           :files ("*")))
#+END_SRC
*** Standard
These are from the [[https://github.com/AndreaCrotti/yasnippet-snippets][official snippets repo]].
#+BEGIN_SRC emacs-lisp
(package! yasnippet-snippets
  :recipe (:host github
           :repo "AndreaCrotti/yasnippet-snippets"
           :files ("*")))
#+END_SRC
** Math support
I like [[https://github.com/cdominik/cdlatex][cdlatex]].
#+BEGIN_SRC emacs-lisp
(package! cdlatex)
#+END_SRC
However, better support for symbols can be found in ~math-symbol-lists~ as [[https://www.emacswiki.org/emacs/TeXInputMethod][discussed here]].
#+begin_src elisp
(package! math-symbol-lists)
#+end_src

# Local Variables:
# eval: (add-hook (quote after-save-hook) (lambda nil (org-babel-tangle)) nil t)
# End:
