#+TITLE: dotDOOM
#+AUTHOR: Rohit Goswami
#+date: 2020:19:01
#+EXPORT_FILE_NAME: index.html
#+OPTIONS: toc:nil
#+STARTUP: nofold

This looks better [[https://dotdoom.grimoire.science][on the website]].

* What?
This is actually a [[https://github.com/hlissner/doom-emacs][doom-emacs]] private module. I was feeling rather whimsical.
** Configuration
This is [[file:config.org][documented here]].
** Packages
I also document the packages I use in a [[file:packages.org][separately here]].
* Why?
[[https://github.com/HaoZeke/Dotfiles][My Dotfiles repo]], managed with the brilliant [[https://github.com/kobus-v-schoor/dotgit][dotgit]], was getting rather overwhelmed
with ~emacs~ commits. Also managing snippets with ~dotgit~ was not exactly
pleasant, since each symlink needed to be listed in the ~filelist~.
** Who?
I'm [[https://orcid.org/0000-0002-2393-8056][Rohit Goswami]] (or HaoZeke, or rg0swami), and well, if you
need to know more about why you might want to use my work, check my [[https:grimoire.science][(outdated)
site]], or any of the [[https:keybase.io/HaoZeke][other sites]] I manage, or even [[https://publons.com/researcher/2911170/rohit-goswami/][my publications]] or [[github:HaoZeke][my code]].
* How?
Well it just goes where ~doom~ expects config files.
#+BEGIN_SRC bash
# Honestly, this should be $HOME/.config
git clone git@github.com:HaoZeke/dotDoom $XDG_CONFIG_DIR/doom
#+END_SRC
* Config
Since the ~config.el~ needs no page of its own, it is simply included below:
#+INCLUDE: "./init.el" src emacs-lisp
* License
It is a personal configuration. So I guess the [[https://choosealicense.com/licenses/mit/][MIT license]] will do for now.
